from django.conf import settings
from django.shortcuts import redirect


class LoginRequiredMiddleware:
    """
    Middleware to enforce login requirement.

    This middleware checks if the user is authenticated for each incoming request.
    If the user is not authenticated and the requested path is not the login URL,
    it redirects the user to the login page.

    Attributes:
        get_response (function): The next middleware or view function in the chain.
    """

    def __init__(self, get_response):
        """
        Initialize the middleware.

        Args:
            get_response (function): The next middleware or view function in the chain.
        """
        self.get_response = get_response

    def __call__(self, request):
        """
        Process the incoming request.

        If the user is not authenticated and the requested path is not the login URL,
        redirect the user to the login page.

        Args:
            request (HttpRequest): The incoming request.

        Returns:
            HttpResponse: The response generated by the next middleware or view function.
        """
        if not request.user.is_authenticated and request.path != settings.LOGIN_URL:
            return redirect(settings.LOGIN_URL)
        return self.get_response(request)
